name: Deploy 

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Log in to Container REGISTRY
        uses: docker/login-action@v4
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Dockere
        id: meta 
        uses: docker/metadata-action@v6 
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: | 
            type=raw,value=latest 
      
      - name: Build & push Docker images 
        uses: docker/build-push-action@v7
        with: 
          context: .
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}