name: Test

on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with: 
          enable-cache: true
      
      - name: Set up Python
        run: uv python install
      
      - name: Install project
        run: uv sync --frozen
      
      - name: Test
        run: uv run poe test
